[package]
name = "vivalaakam_neat_rs"
version = "0.1.16"
edition = "2021"
authors = ["Andrey Makarov <viva.la.akam@gmail.com>"]
description = "Library for calculation some things"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
tracing = "0.1"
serde_json = "1.0"
new_york_utils = "0.1"
serde = { version = "1.0", features = ["derive"] }
strum = { version = "0.24", features = ["derive"] }
getrandom = { version = "0.2.7", features = ["js"] }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "activate"
harness = false

[dependencies.tracing-subscriber]
version = "0.3"

[dependencies.csv]
version = "1.2"
