[package]
name = "vivalaakam_neat_rs"
version = "0.1.4"
edition = "2021"
authors = ["Andrey Makarov <viva.la.akam@gmail.com>"]
description = "Library for calculation some things"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
rand = "0.8"
env_logger = "0.9"
serde_json = "1.0"
new_york_utils = "0.1"
serde = { version = "1.0", features = ["derive"] }
getrandom = { version = "0.2.7", features = ["js"] }

