[workspace]
resolver = "2"

members = [
    "examples",
    "neat",
    "utils",
]

[workspace.dependencies]
rand = "0.8"
bytes = "1.5"
tracing = "0.1"
ndarray = "0.15"
thiserror = "1.0"
serde_json = "1.0"
new_york_utils = "0.1"
vivalaakam_neuro_neat = { path = "./neat" }
vivalaakam_neuro_utils = { path = "./utils" }
getrandom = { version = "0.2", features = ["js"] }
serde = { version = "1.0", features = ["derive"] }
strum = { version = "0.25", features = ["derive"] }
